name: Rust

on:
  push:
    branches: [ 3.x ]
  pull_request:
    branches: [ 3.x ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Cargo test
      run: cargo test --verbose --no-fail-fast
    - name: Build Release
      run: cargo build --verbose --release
    - name: Download test files
      run: ./script/ci-download.sh
    - name: Test
      run: ./script/ci-run.sh
    - uses: actions/upload-artifact@v3
      with:
        name: linux-artifact
        path: |
          target/debug/chrome-pak-customizer
          target/release/chrome-pak-customizer

  build-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Cargo test
        run: cargo test --verbose --no-fail-fast
      - name: Build Release
        run: cargo build --verbose --release
      - name: Download test files
        run: PowerShell.exe -ExecutionPolicy Bypass -File ./script/ci-download.ps1
      - name: Test
        run: PowerShell.exe -ExecutionPolicy Bypass -File ./script/ci-run.ps1
      - uses: actions/upload-artifact@v3
        with:
          name: windows-artifact
          path: |
            target/debug/*.exe
            target/release/*.exe

  build-macos:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Cargo test
        run: cargo test --verbose --no-fail-fast
      - name: Build Release
        run: cargo build --verbose --release
      - name: Download test files
        run: ./script/ci-download.sh
      - name: Install coreutils
        run: brew install coreutils
      - name: Test
        run: ./script/ci-run.sh
      - uses: actions/upload-artifact@v3
        with:
          name: macos-artifact
          path: |
            target/debug/chrome-pak-customizer
            target/release/chrome-pak-customizer
